name: Deploy

on:
  push:
    branches:
      - master # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PATH: /home/runner/work/github-cicd/github-cicd/node_modules/.bin:$PATH
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        echo -e "Host ec2-13-53-207-20.eu-north-1.compute.amazonaws.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        ssh -i keyfile ubuntu@ec2-13-53-207-20.eu-north-1.compute.amazonaws.com "sudo bash -c 'cd ~/github-cicd && git pull origin master && cd server && pm2 kill && pm2 start index.js'"

